package com.sinnbo.jfinal.domain.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysController<M extends BaseSysController<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setControllerName(java.lang.String controllerName) {
		set("controller_name", controllerName);
	}

	public java.lang.String getControllerName() {
		return get("controller_name");
	}

	public void setControllerKey(java.lang.String controllerKey) {
		set("controller_key", controllerKey);
	}

	public java.lang.String getControllerKey() {
		return get("controller_key");
	}

	public void setControllerValue(java.lang.String controllerValue) {
		set("controller_value", controllerValue);
	}

	public java.lang.String getControllerValue() {
		return get("controller_value");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}

	public java.lang.String getNote() {
		return get("note");
	}

	public void setDataStatus(java.lang.Integer dataStatus) {
		set("data_status", dataStatus);
	}

	public java.lang.Integer getDataStatus() {
		return get("data_status");
	}

}
