package com.sinnbo.jfinal.domain.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOnlineOrder<M extends BaseOnlineOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setOrderNum(java.lang.String orderNum) {
		set("order_num", orderNum);
	}

	public java.lang.String getOrderNum() {
		return get("order_num");
	}

	public void setCustomerId(java.lang.Integer customerId) {
		set("customer_id", customerId);
	}

	public java.lang.Integer getCustomerId() {
		return get("customer_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setFinishStatus(java.lang.Integer finishStatus) {
		set("finish_status", finishStatus);
	}

	public java.lang.Integer getFinishStatus() {
		return get("finish_status");
	}

	public void setFinishTime(java.util.Date finishTime) {
		set("finish_time", finishTime);
	}

	public java.util.Date getFinishTime() {
		return get("finish_time");
	}

	public void setDataStatus(java.lang.Integer dataStatus) {
		set("data_status", dataStatus);
	}

	public java.lang.Integer getDataStatus() {
		return get("data_status");
	}

}
