package com.sinnbo.jfinal.domain.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOfflineOrder<M extends BaseOfflineOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSkuId(java.lang.Integer skuId) {
		set("sku_id", skuId);
	}

	public java.lang.Integer getSkuId() {
		return get("sku_id");
	}

	public void setCount(java.lang.Integer count) {
		set("count", count);
	}

	public java.lang.Integer getCount() {
		return get("count");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setEmployee(java.lang.Integer employee) {
		set("employee", employee);
	}

	public java.lang.Integer getEmployee() {
		return get("employee");
	}

}
