package com.sinnbo.jfinal.domain;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("i_basic_batch", "id", BasicBatch.class);
		arp.addMapping("i_basic_customer", "id", BasicCustomer.class);
		arp.addMapping("i_basic_employee", "id", BasicEmployee.class);
		arp.addMapping("i_basic_item", "id", BasicItem.class);
		arp.addMapping("i_basic_item_remain", "id", BasicItemRemain.class);
		arp.addMapping("i_basic_item_sku", "id", BasicItemSku.class);
		arp.addMapping("i_basic_role_user", "id", BasicRoleUser.class);
		arp.addMapping("i_basic_roles", "id", BasicRoles.class);
		arp.addMapping("i_basic_sku_remain", "id", BasicSkuRemain.class);
		arp.addMapping("i_basic_user", "id", BasicUser.class);
		arp.addMapping("i_dict_area", "id", DictArea.class);
		arp.addMapping("i_offline_order", "id", OfflineOrder.class);
		arp.addMapping("i_online_order", "id", OnlineOrder.class);
		arp.addMapping("i_online_order_customer", "id", OnlineOrderCustomer.class);
		arp.addMapping("i_sys_controller", "id", SysController.class);
		arp.addMapping("i_sys_menu", "id", SysMenu.class);
		arp.addMapping("i_sys_role_controller", "id", SysRoleController.class);
	}
}

