package com.sinnbo.jfinal.domain;

import com.sinnbo.jfinal.domain.base.BaseBasicRoleUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasicRoleUser extends BaseBasicRoleUser<BasicRoleUser> {
	public static final BasicRoleUser dao = new BasicRoleUser();
}
