package com.sinnbo.jfinal.domain;

import com.sinnbo.jfinal.common.enumwork.DataStatus;
import com.sinnbo.jfinal.domain.base.BaseBasicUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasicUser extends BaseBasicUser<BasicUser> {
//  private final static Logger logger = Logger.getLogger("BasicUser");
  public static final BasicUser dao = new BasicUser();
	
//  private static LoadingCache<Integer, BasicUser> cache = CacheBuilder.newBuilder()
//      .maximumSize(1000).build(new CacheLoader<Integer, BasicUser>() {
//            @Override
//            public BasicUser load(Integer id) throws Exception {
//              return dao.findById(id);
//            }
//  });
//  
//  public BasicUser getByCache(Integer id) {
//    try {
//      return cache.get(id);
//    } catch (Exception e) {
//      logger.info("找不到id="+id+"的" + getClass() + "对象");
//      return null;
//    }
//  }
//
//  public void invalidateCache(Integer id) {
//    cache.invalidate(id);
//  }

  public BasicUser getByUserName(String userName) {
    return dao.findFirst("select * from i_basic_user where user_name=? and data_status=?", userName, DataStatus.ENABLED.getValue());
  }
}
