package com.sinnbo.jfinal.domain;

import com.sinnbo.jfinal.domain.base.BaseBasicEmployee;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasicEmployee extends BaseBasicEmployee<BasicEmployee> {
	public static final BasicEmployee dao = new BasicEmployee();
}
