package com.sinnbo.jfinal.domain;

import com.sinnbo.jfinal.domain.base.BaseBasicItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasicItem extends BaseBasicItem<BasicItem> {
	public static final BasicItem dao = new BasicItem();
}
