package com.sinnbo.jfinal.domain;

import com.sinnbo.jfinal.domain.base.BaseBasicRoles;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasicRoles extends BaseBasicRoles<BasicRoles> {
	public static final BasicRoles dao = new BasicRoles();
}
