package com.sinnbo.jfinal.domain;

import com.sinnbo.jfinal.domain.base.BaseBasicItemSku;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasicItemSku extends BaseBasicItemSku<BasicItemSku> {
	public static final BasicItemSku dao = new BasicItemSku();
}
