package com.sinnbo.jfinal.domain;

import com.sinnbo.jfinal.domain.base.BaseBasicCustomer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasicCustomer extends BaseBasicCustomer<BasicCustomer> {
	public static final BasicCustomer dao = new BasicCustomer();
}
