package com.sinnbo.jfinal.domain;

import com.sinnbo.jfinal.domain.base.BaseBasicItemRemain;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasicItemRemain extends BaseBasicItemRemain<BasicItemRemain> {
	public static final BasicItemRemain dao = new BasicItemRemain();
}
