package com.sinnbo.jfinal.domain;

import com.sinnbo.jfinal.domain.base.BaseBasicSkuRemain;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasicSkuRemain extends BaseBasicSkuRemain<BasicSkuRemain> {
	public static final BasicSkuRemain dao = new BasicSkuRemain();
}
