package com.sinnbo.jfinal.domain;

import com.sinnbo.jfinal.domain.base.BaseBasicBatch;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasicBatch extends BaseBasicBatch<BasicBatch> {
	public static final BasicBatch dao = new BasicBatch();
}
