package com.sinnbo.jfinal.domain;

import com.sinnbo.jfinal.domain.base.BaseDictArea;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DictArea extends BaseDictArea<DictArea> {
	public static final DictArea dao = new DictArea();
}
