package com.sinnbo.jfinal.domain;

import com.sinnbo.jfinal.domain.base.BaseOfflineOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OfflineOrder extends BaseOfflineOrder<OfflineOrder> {
	public static final OfflineOrder dao = new OfflineOrder();
}
