package com.sinnbo.jfinal.domain;

import com.sinnbo.jfinal.domain.base.BaseOnlineOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OnlineOrder extends BaseOnlineOrder<OnlineOrder> {
	public static final OnlineOrder dao = new OnlineOrder();
}
