package com.sinnbo.jfinal.domain;

import com.sinnbo.jfinal.domain.base.BaseOnlineOrderCustomer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OnlineOrderCustomer extends BaseOnlineOrderCustomer<OnlineOrderCustomer> {
	public static final OnlineOrderCustomer dao = new OnlineOrderCustomer();
}
