package com.sinnbo.jfinal.domain;

import com.sinnbo.jfinal.domain.base.BaseSysBackgroudImg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysBackgroudImg extends BaseSysBackgroudImg<SysBackgroudImg> {
	public static final SysBackgroudImg dao = new SysBackgroudImg();
}
