package com.sinnbo.jfinal.domain;

import com.sinnbo.jfinal.domain.base.BaseSysController;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysController extends BaseSysController<SysController> {
	public static final SysController dao = new SysController();
}
