package com.sinnbo.jfinal.domain;

import java.util.List;

import com.sinnbo.jfinal.common.enumwork.DataStatus;
import com.sinnbo.jfinal.domain.base.BaseSysMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysMenu extends BaseSysMenu<SysMenu> {
	public static final SysMenu dao = new SysMenu();
	
	public List<SysMenu> getAll() {
	  return find("select * from i_sys_menu where data_status!=?", DataStatus.DELETED.getValue());
	}
}
