package com.sinnbo.jfinal.domain;

import com.sinnbo.jfinal.domain.base.BaseSysRoleController;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleController extends BaseSysRoleController<SysRoleController> {
	public static final SysRoleController dao = new SysRoleController();
}
